name: flutter_fundamental_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.2.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    fonts:
        - family: Montserrat
          fonts:
              - asset: fonts/Montserrat-Regular.ttf
              - asset: fonts/Montserrat-Italic.ttf
                style: italic
              - asset: fonts/Montserrat-Bold.ttf
                weight: 700
              - asset: fonts/Montserrat-BoldItalic.ttf
                weight: 700
                style: italic
