name: week_11
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.2.6 <4.0.0"

dependencies:
    dropdown_search: ^5.0.6
    flutter:
        sdk: flutter
    flutter_launcher_icons: ^0.13.1
    http: ^1.2.0

flutter_launcher_icons:
    image_path_android: "lib/flutter_launcher_icon/images/launcher.png"
    android: true

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
