name: flutter_week9
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  avatar_glow: ^3.0.1
  convex: ^0.0.3+1
  convex_bottom_bar: ^3.2.0
  faker: ^2.1.0
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  http: ^1.2.0
  intl: ^0.19.0
  introduction_screen: ^3.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
